#Dockerfile.fastapi
FROM nvidia/cuda:12.1.0-cudnn8-runtime-ubuntu22.04

# Install Python y basic dependencies
RUN apt-get update && apt-get install -y \
    python3.11 python3-pip python3.11-venv \
    curl pciutils lshw && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
ENV VIRTUAL_ENV=/opt/venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN python -m venv $VIRTUAL_ENV \
    && pip install --upgrade pip

# Dependencys
COPY backend-llm/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Embedding library
COPY embedding_utils /app/embedding_utils
RUN pip install --no-cache-dir /app/embedding_utils

# App
COPY backend-llm/app/ ./app

EXPOSE 8000
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
